#pragma once

#define MACHINE_NAME            "Chessato"
#define CUSTOM_CODE_FILENAME    "../Custom/CoreXY.cpp"

#define N_AXIS 2

#define TRINAMIC_UART_RUN_MODE TrinamicUartMode ::StealthChop
#define TRINAMIC_UART_HOMING_MODE TrinamicUartMode ::StallGuard

#define TMC_UART UART_NUM_1
#define TMC_UART_RX GPIO_NUM_21
#define TMC_UART_TX GPIO_NUM_22 


#define X_TRINAMIC_DRIVER 2209
#define X_STEP_PIN  GPIO_NUM_12
#define X_DIRECTION_PIN  GPIO_NUM_14
#define X_RSENSE TMC2209_RSENSE_DEFAULT
#define X_DRIVER_ADDRESS 0
#define DEFAULT_X_MICROSTEPS 16

#define Y_TRINAMIC_DRIVER 2209
#define Y_STEP_PIN GPIO_NUM_26
#define Y_DIRECTION_PIN GPIO_NUM_27
#define Y_RSENSE TMC2209_RSENSE_DEFAULT
#define Y_DRIVER_ADDRESS 1
#define DEFAULT_Y_MICROSTEPS 16


#define X_LIMIT_PIN  GPIO_NUM_13
#define Y_LIMIT_PIN  GPIO_NUM_19
//#define SPINDLE_ENABLE_PIN GPIO_NUM_5
